<?php 
error_reporting(0);
if ($_POST) {
$dbhost=("localhost");
$dbuser=$_POST['dbuser'];
$dbpass=$_POST['dbpass'];
$dbdata=$_POST['dbdata'];
$spexcon=('$spexcon');
$spexconn=('$spexcon->set_charset');
$ac = fopen("../app/config.php", 'a+');
fwrite($ac, "
<?php
/*       @spexcoder         */
/*  Auto Generated by SpeX  */

  $spexcon = new mysqli(

  'localhost',  
  
  '$dbuser',  
  
  '$dbpass',    
  
  '$dbdata'
);
$spexconn('UTF-8'); 
// SpeX CodeR  TG -> SANAHASRET
// SpeX CodeR  MYSQL BAGLANTİSİ
// SpeX CodeR  İG -> SPEXCODER
?>
");
fclose($ac);
ob_start(); 
include '../app/database/DBBackupRestore.class.php';
$dbBackup = new DBYedek(); 
	$dosya = '../app/database/spexmulti.sql';
    $maxKomut = 8;
	$dbBackup->Ice_Aktar($dosya, $maxKomut); 
$dbBackup->kapat();
ob_end_flush();
}
$adminuser=$_POST['adminuser'];
$adminpass=$_POST['adminpass'];
include ("../app/config.php");
$güncelle31 = $spexcon->query("UPDATE `admin` SET user='".$adminuser."', pass='".$adminpass."' WHERE 1");
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Config Z-Panel V6</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">	
	<script src='https://unpkg.com/sweetalert/dist/sweetalert.min.js'></script>	
<style>
body {
  font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif; 
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
  background-color: black;
}	
</style>
</head>
<body>
<center>
<div class="container">
<br><br><br><br><br><br><br><br>	
	<div class="row" style="margin-top: -300px;">
		<center>
		<h3><b><font color="white">Kurulum Tamamlandı!</font></b></h3>
    <b><p><font color="green">SQL Başarıyla Aktarıldı.</font></p></b>
	  <br><br>
    <a href="../admin/index.php"><button class="btn btn-danger" style="width: 320px;">Go Dashboard</button></a> <br><br>
    <a href="../index.php"><button class="btn btn-warning" style="width: 320px;">Visit Home Page</button></a> <br> <br>
    <a href="https://www.instagram.com/spexcoder"><button class="btn btn-info" style="width: 320px;">Follow Me</button></a> <br>  
		</center>
	</div>
</div>
</center>	 		
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>	
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>